#正在启动的环境
spring:
  profiles:
  label: master
    active:
      - dev

---
#开发环境配置
spring:
  profiles: dev
  label: master
  application:
    name: config-dev

---
#测试环境配置
spring:
  profiles:
  label: master
  application:
    name: config-test
#请保存为UTF-8编码格式

  