#激活使用的模块remote use
spring:
  label: master
  profiles:
    active: dev
---
#服务注册中心2001-dev开发模块配置
server:
  port: 2001
spring:
  label: master
  profiles: dev
  application:
    name: config-eureka
eureka:
  instance:
    hosthome: localhost
  client.register-with-eureka: false
  client.fetch-registry: false
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/,http://localhost:1001/eureka/,http://localhost:2001/eureka/
---

#服务注册中心200-test测试模块1配置
#server:
#  port: 2001
#spring:
#profiles: test
#application:
#  name: config-eureka
#
#eureka:
#  instance:
#    hosthome: eureka2001.com
#  client.register-with-eureka: false
#  client.fetch-registry: false
#  client:
#    service-url:
#      defaultZone: defaultZone: http://localhost:1000/eureka/,http://localhost:1001/eureka/