#spring-cloud-config-client //idea中模块的配置文件
server:
  port: 1011
spring:
  label: master
  profiles: dev
  application:
     name: spring-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka1000.com:1000/eureka/,http://eureka1001.com:1001/eureka/,http://eureka2001.com:2001/eureka/
---
server:
  port: 1012
spring:
  label: master
  profiles: test
  application:
    name: spring-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka1000.com:1000/eureka/,http://eureka1001.com:1001/eureka/,http://eureka2001.com:2001/eureka/